# .gitlab-ci.yml
image: node:latest

pages:
  image: cr.yealinkops.com/common/yarn:1.19.1
  stage: deploy
  tags:
    - devops_docker_runner
  cache:
    paths:
      - node_modules/
      - yarn.lock
  script:
    - yarn install -f
    - yarn run build:website
    - ls
    - ls dist
    - ls dist/website
    - mv public public-bak # GitLab Pages 的钩子设置在 public 文件夹
    - mv dist/website public # 重命名 dist 文件夹 (yarn run build:website 之后的输出位置)
  artifacts:
    paths:
      - public # artifact path 一定要在 /public , 这样 GitLab Pages 才能获取
  only:
    - master