# .gitlab-ci.yml
image: node:latest

line:
  image: cr.yealinkops.com/common/yarn:1.19.1
  stage: build
  tags:
    - devops_docker_runner
  cache:
    paths:
      - node_modules/
      - yarn.lock
  script:
    - yarn install -f
    - yarn run build line --release
    - mkdir -p public/line
    - mv packages/line/dist public/line/dist
  only:
    - master

pages:
  image: cr.yealinkops.com/common/yarn:1.19.1
  stage: deploy
  tags:
    - devops_docker_runner
  cache:
    paths:
      - node_modules/
      - yarn.lock
  script:
    - yarn install -f
    - yarn run build template-explorer
    - mv packages/template-explorer public/template-explorer
#    - mv public public-bak # GitLab Pages 的钩子设置在 public 文件夹
#    - mv dist/website public # 重命名 dist 文件夹 (yarn run build:website 之后的输出位置)
  artifacts:
    paths:
      - public # artifact path 一定要在 /public , 这样 GitLab Pages 才能获取
  only:
    - master