// Global compile-time constants
declare const __DEV__: boolean;
declare const __TEST__: boolean;
declare const __BROWSER__: boolean;
declare const __BUNDLER__: boolean;
declare const __ESM_BROWSER__: boolean;
declare const __ESM_BUNDLER__: boolean;
declare const __GLOBAL__: boolean;
declare const __NODE_JS__: boolean;
declare const __COMMIT__: string;
declare const __VERSION__: string;
